import type { Metadata } from "next";
import { Geist, Geist_Mono, Lato, Manrope, Montserrat } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});
// const geistLato = Lato({
//   variable: "--font-lato",
//   subsets: ["latin"],
// });
const manrope = Manrope({
  variable: "--font-manrope",
  subsets: ["latin"],
});
const geistMontserra = Montserrat({
  variable: "--font-monoserra",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} ${manrope.variable} ${geistMontserra.variable} antialiased`}
      >
        <main className="flex-1 overflow-y-auto">{children}</main>
      </body>
    </html>
  );
}
